name: star
channels:
  - conda-forge
  - bioconda 
  - defaults 

dependencies: 
  - star =2.7.6a
  - r-base=4.0.2
  - r-tidyverse
  - r-data.table
  - r-ggplot2
  - r-markdown
  - r-pheatmap
  - bioconductor-deseq2
  - bioconductor-annotationhub
  - bioconductor-tximport
  - bioconductor-rsubread
